//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Fresher.CukCuk.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Fresher.CukCuk.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu câu hỏi thành công.
        /// </summary>
        public static string AddExerciseSuccess {
            get {
                return ResourceManager.GetString("AddExerciseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin giáo viên thành công.
        /// </summary>
        public static string AddTeacherSuccess {
            get {
                return ResourceManager.GetString("AddTeacherSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bài tập thành công.
        /// </summary>
        public static string DeleteExerciseSuccess {
            get {
                return ResourceManager.GetString("DeleteExerciseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thông tin các giáo viên thành công.
        /// </summary>
        public static string DeleteMultiTeacherSuccess {
            get {
                return ResourceManager.GetString("DeleteMultiTeacherSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thông tin giáo viên thành công.
        /// </summary>
        public static string DeleteTeacherSuccess {
            get {
                return ResourceManager.GetString("DeleteTeacherSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ chuyên môn.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin giáo viên thành công.
        /// </summary>
        public static string EditTeacherSuccess {
            get {
                return ResourceManager.GetString("EditTeacherSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng. Vui lòng kiểm tra lại.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo QLTB.
        /// </summary>
        public static string EquipmentQualification {
            get {
                return ResourceManager.GetString("EquipmentQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý kho - phòng.
        /// </summary>
        public static string EquipmentRoomName {
            get {
                return ResourceManager.GetString("EquipmentRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le Minh Duc.
        /// </summary>
        public static string ExcelAuthor {
            get {
                return ResourceManager.GetString("ExcelAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_can_bo_giao_vien.xlsx.
        /// </summary>
        public static string ExcelName {
            get {
                return ResourceManager.GetString("ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách Cán bộ - Giáo viên.
        /// </summary>
        public static string ExcelTitle {
            get {
                return ResourceManager.GetString("ExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất khẩu danh sách giáo viên thành công.
        /// </summary>
        public static string ExportTeacherSuccess {
            get {
                return ResourceManager.GetString("ExportTeacherSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường thông tin không được phép để trống.
        /// </summary>
        public static string FieldEmpty {
            get {
                return ResourceManager.GetString("FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên giáo viên không được phép để trống.
        /// </summary>
        public static string FullNameEmpty {
            get {
                return ResourceManager.GetString("FullNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy mã giáo viên mới thành công.
        /// </summary>
        public static string GetNewTeacherCodeSuccess {
            get {
                return ResourceManager.GetString("GetNewTeacherCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy danh sách giáo viên thành công.
        /// </summary>
        public static string GetTeacherSuccess {
            get {
                return ResourceManager.GetString("GetTeacherSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số truyền vào không hợp lệ. Vui lòng kiểm tra lại.
        /// </summary>
        public static string ParamInvalid {
            get {
                return ResourceManager.GetString("ParamInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp.
        /// </summary>
        public static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Stt {
            get {
                return ResourceManager.GetString("Stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thiết bị môn.
        /// </summary>
        public static string SubjectName {
            get {
                return ResourceManager.GetString("SubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu cán bộ.
        /// </summary>
        public static string TeacherCode {
            get {
                return ResourceManager.GetString("TeacherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giáo viên không được phép để trống.
        /// </summary>
        public static string TeacherCodeEmpty {
            get {
                return ResourceManager.GetString("TeacherCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giáo viên phải kết thúc bằng chữ số. Vui lòng kiểm tra lại.
        /// </summary>
        public static string TeacherCodeEndNumber {
            get {
                return ResourceManager.GetString("TeacherCodeEndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giáo viên đã tồn tại trong hệ thống. Vui lòng kiểm tra lại.
        /// </summary>
        public static string TeacherCodeExist {
            get {
                return ResourceManager.GetString("TeacherCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách CBTB.
        /// </summary>
        public static string WorksheetName {
            get {
                return ResourceManager.GetString("WorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH CÁN BỘ - GIÁO VIÊN.
        /// </summary>
        public static string WorksheetTitle {
            get {
                return ResourceManager.GetString("WorksheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc.
        /// </summary>
        public static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
    }
}
